# Generated by Django 2.2.2 on 2019-06-14 03:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('list_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('card_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due_date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.List')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='board_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
