# Generated by Django 2.2.2 on 2019-06-14 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190614_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='list_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='list',
            name='card_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
