version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile

    command: >
      bash -c "python manage.py migrate
      && python manage.py test
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
